name: Check site validity

env:
  ZOLA_VERSION: 0.21.0

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    environment: production
    name: Check Zola build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Zola
        run: |
          wget -O zola.tar.gz -c https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          tar -zxvf zola.tar.gz
          ./zola build
